### ISSUE TITLE
Convert MilightColor back to HSV

### ISSUE THREAD

**Issue by Xento** [Xento/node-milight-rf24#1]
@mwittig could you help me with this issue?
You wrote the conversion from hsv to milightcolor.

color = (256 + 26 - Math.floor(Number(hsv[0]) / 360.0 \* 255.0)) % 256;

**Comment by mwittig** [comment]
Sure. See http://en.wikipedia.org/wiki/HSL_and_HSV for an overview on the HSV color model. 

hsv[0] refers to the the hue color circle (= 360 degrees) which needs to be mapped to the 256 hue presets available with Milight. If you imagine the the Milight hue presets as a circle (see http://goo.gl/AM0kEA for example) and compare it to the hue color circle, the Milight circle appears to be shifted counter-clockwise. For example HSV blue located at about 2 o'clock is located at 12 o'clock on the Milight circle. 

See also https://jsfiddle.net/WittigMarcus/p0xw0jks/ which is the mapping the other way round from Milight to HSV which then is mapped to RGB to set a CSS background color for a given value of the slider. The slider value is a Milight color preset (0 .. 255, plus 256 used to switch to white mode).

Note beyond, it is not possible to control saturation with Milight. Brightness can be seen (more or less) as value of HSV, but Milight has only 19 brightness presets.

**Comment by mwittig** [comment]
You could please also do me a favor: Do you have a schematic for a openmilli hardware based on PL1167? Is this what you are using?

**Comment by Xento** [comment]
No I'm using a normal nrf24 module. 
First I tried to modificate a milight receiver to replace the microcontroler but then henryke wrote a transceiver sketch using a nrf24. 
As you can see I'm working on an milightrf24 device for the pimatic-led-light plugin with receiving from other remotes.

**Comment by mwittig** [comment]
Thanks.
