### ISSUE TITLE
how to get "addr" for control in pimatic?

### ISSUE THREAD

**Issue by xCite1986** [Xento/node-milight-rf24#2]
hey xento.

i'm trying to control a [milight-module](https://www.amazon.de/Wireless-Steuermodul-Controller-Lampe-Licht/dp/B00KF9W7ES/ref=sr_1_3?ie=UTF8&qid=1460901775&sr=8-3&keywords=milight) with an nfr and arduino, but i have no remote to receive an "addr" to add it in pimatic

was it possible to get them without an remote work?

https://forum.pimatic.org/topic/332/plugin-for-wifi-controlled-led-light-iwy-light/140

thanks in advance

**Comment by Xento** [comment]
Then you can set your own.
The address has to be 3 bytes long for example B01234
